### ISSUE TITLE
How to use gemini key in google aistudio

### ISSUE THREAD

**Issue by hoangquocvietbro** [Huanshere/VideoLingo#407]
Can i use gemini key in google aistudio or not?
How it work, How i can setup it

**Comment by Huanshere** [comment]
Sure! Now google support openai format,

Set in config.yaml:
```
api:
  key: 'AIza... your key here'
  base_url: 'https://generativelanguage.googleapis.com/v1beta/openai/'
  model: 'gemini-2.0-flash'
```

Also, set max_workers=1 if you're using free model
